AWSTemplateFormatVersion: 2010-09-09
Description: Jira / Confluence Server to DC (AWS) Helper

Resources:

  MigrationBucket:
    Type: AWS::S3::Bucket
    DependsOn: QueuePolicy
    Properties:
      BucketName: !Sub 'atl-migrationbucket-${AWS::StackName}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: !GetAtt MigrationQueue.Arn
            Event: s3:ObjectCreated:*
    DeletionPolicy: Delete

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn: MigrationQueue
    Properties:
      PolicyDocument:
        Id: !Sub "MigrationQueue_Policy_${AWS::AccountId}"
        Version: 2012-10-17
        Statement:
          - Sid: "MigrationQueue_SendMessage"
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - SQS:SendMessage
            Resource: !GetAtt MigrationQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt MigrationBucket.Arn
      Queues:
        - !Ref MigrationQueue

  MigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 864000
      QueueName: !Sub 'atl-migration-queue-${AWS::StackName}'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 90

  JiraFilePathParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /config/migration-helper/app.jira.file.path
      Type: String
      Value: '/efs/jira/shared'
      Description: File Path

  RegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /config/migration-helper/app.region.id
      Type: String
      Value: !Ref AWS::Region
      Description: Region Name